```{r load_data}
# if(!require(crimedata)) install.packages("crimedata")                           #loads crime data package for CODE data
# list_crime_data()                                                               #callsfrom r package crimedata
# 
# df <- get_crime_data(                                                           #Boston data only
#   cities="Boston"
#   , type = 'extended'
#   , years = 2016:2021  
# )
# 
# key_bos_district =  c(A1 = 'Downtown', A7 = 'East Boston', A15 = 'Charlestown',  B2 = 'Roxbury', B3 = 'Mattapan', C6 = 'South Boston', C11 = 'Dorchester', D4 = 'South End', D14 = 'Allston/Brighton', E5 = 'West Roxbury', E13 = 'Jamaica Plain', E18 = 'Hyde Park',.default = NA)
# df$bos_district_name <- recode(df$bos_district, !!!key_bos_district)
# # https://bostonpal.org/district-officers/
```

```{r table1_offense_type}
#count number of crime offense types
df_offense <-data.frame(count(df, offense_type))         #count the number of offense_types
df_offense <- arrange(df_offense,  -n)                   #negative n is so that values descend instead of ascend
df_offense<- df_offense %>%                              #rename column n_total for total number of crimes 2016-2021
 rename(n_total=n, 'Offense type'=offense_type)
df_offense <- df_offense %>%                             #get mean number of crimes
   mutate('Count of crimes per year' = n_total/6) 
df_offense$'Count of crimes per year' <- round(df_offense$'Count of crimes per year', digits=0)  #round the mean number of crimes
df_offense$'% of total offenses' <- round(df_offense$'Count of crimes per year'/(sum(df_offense$'Count of crimes per year'))*100, digits=2)
rename_with(df_offense,toupper)                          #Renames column names to upper
df_offense %>%                                           #wanted to make offense type column to title case; ineffective.
  mutate('Offense type' = stringr::str_to_title('Offense type'))

#top 5 crime offenses
top_5_crimes <- df_offense %>%
  select(-n_total) %>%
  head(5)
top_5_crimes

#format and export table1 top 5 crimes
library(kableExtra)
table1 <- knitr::kable(top_5_crimes, format = "html", caption = "Table 1", font_size = 20) %>%
  kable_styling(bootstrap_options = "basic",
                full_width = F,
                position = "float_left",
                font_size = 20) %>%
  kableExtra::kable_classic_2(bootstrap_options = c("striped", "hover"))%>%
  kableExtra::add_footnote(c("Number of crimes are reported as the average number offenses for years 2016-2021."), notation='none') 
table1

table1 %>%                                                #save table as jpeg
  kableExtra::save_kable("C:/Users/ ... /table1_top_5_offense_types.jpeg", density = 900)
table1

#format and export table1 all crimes
all_crimes <- df_offense %>%
  select(-n_total) 
all_crimes

library(kableExtra)
table_1_all <- knitr::kable(all_crimes, format = "html", caption = "Table 1", font_size = 20) %>%
  kable_styling(bootstrap_options = "basic",
                full_width = F,
                position = "float_left",
                font_size = 20
                ) %>%
  kableExtra::kable_classic_2(bootstrap_options = c("striped", "hover"))%>%
  kableExtra::add_footnote(c("Number of crimes are reported as the average number offenses for years 2016-2021."), notation='none') 
table_1_all

table_1_all %>%                                                #save table as jpeg
  kableExtra::save_kable("C:/Users/ ... /table1_all_offenses.jpeg", density = 900)
table_1_all
```
